services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "10"
      RAM_SIZE: "5G"
      CPU_CORES: "8"
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 9000:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
